; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:esp32-c3-devkitm-1]
platform = espressif32@6.5.0  ; 使用 ESP32-C3 Super Mini
board = esp32-c3-devkitm-1

; [env:airm2m_core_esp32c3]
; platform = espressif32@6.5.0
; board = airm2m_core_esp32c3   ; 使用合宙 CORE ESP32

framework = arduino
board_build.partitions = partitions.csv

board_build.stack_size = 16384

; ========== 串口监视器配置 ==========
monitor_speed = 115200
upload_port = COM9
monitor_port = COM9
board_upload.speed = 115200

; ========== LovyanGFX 驱动配置 ==========
lib_deps = 
    lovyan03/LovyanGFX
    adafruit/DHT sensor library
    knolleary/PubSubClient @ ^2.8

build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

; ========== 文件系统配置 ==========
board_build.filesystem = spiffs
